version: "2.4"

services:
  db:
    image: mariadb:10.4.12
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "minitwit"
      MYSQL_USER: "root"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./schemal.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306

  server:
    build:
      context: .
      target: production
    volumes:
      - .:/usr/app:delegated
    ports:
      - 80:3000
