version: "2.3"

services:
  db:
    image: mariadb:10.4.12
    restart: always
    env_file: 
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u$MYSQL_USER", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
    volumes: 
      - ./db:/var/lib/mysql
      - ./db.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3307:3306

  server:
    build:
      context: .
      target: dev
    restart: always
    env_file: 
      - .env
    volumes: 
      - .:/usr/app:delegated
    ports:
      - 80:3000
      - 5001:5001
    depends_on: 
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:4.5.2
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "4000:3000"  