version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: echo $DOCKER_PASSWORD | docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Build minitwit docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            else
              DOCKER_TAG="latest"
            fi
            docker build -t $DOCKER_USER/minitwit:${DOCKER_TAG} . -f Dockerfile
      - run:
          name: Push to DockerHub
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            else
              DOCKER_TAG="latest"
            fi
            docker push $DOCKER_USER/minitwit:${DOCKER_TAG}
    lint:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: yarn install
        - run:
            name: Linting
            command: yarn lint

workflows:
  version: 2
  commit:
    jobs:
      - build
      - lint
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
