version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Build minitwit docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            elif
              DOCKER_TAG="latest"
            fi
            docker build -t $DOCKER_USERNAME/minitwit:${DOCKER_TAG} . -f Dockerfile
      - run:
          name: Push to DockerHub
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            elif
              DOCKER_TAG="latest"
            fi
            docker push $DOCKER_USERNAME/minitwit:${DOCKER_TAG}

workflows:
  version: 2
  commit:
    jobs:
      - build
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
